### ISSUE TITLE
Generate an "all (named) nodes" supertype?

### ISSUE THREAD

**Issue by wldmr** [Jakobeha/type-sitter#5]
When iterating over a file I find myself missing a supertype that encompasses _all_ grammar elements (or at least the named ones). An example would be a formatter, where you'll want to make sure you don't miss any nodes (especially on a moving target, like the [wldmr/tree-sitter-ink](https://github.com/wldmr/tree-sitter-ink) grammar that I'm developing.

So I've done the smallest change that solves my problem [here](https://github.com/Jakobeha/type-sitter/compare/main...wldmr:type-sitter:synthetic-nodes#diff-96a4eb01efefd6837eb85e3830d889d7650414a299f085616dcf24a16815d914L69-L72). It basically just wedges in the three new supertypes in the `NodeTypeMap::new()` function.

I was thinking about maybe exposing an `insert()` method on `NodeTypeMap` and making `parse_node_type_map()` public, so users then could postprocess it themselves before writing it out. But that would mean making all of the innards public as well, so I wanted to consult you first.

My general question would be: Do you think this is something that you would want this library to offer, and if so, how?

I'm happy to implement this, if you're willing to help me along a bit (haven't fully grokked the code yet).

If not, do you think there's another/better way to get exhaustive (compile time) matching on all nodes?

**Comment by Jakobeha** [comment]
I think this is a good change. If you change the generated `sexp_name`s to `_all_named`, `_all_unnamed`, and `_all_nodes` and submit a PR I'll merge.

I'm fine with exposing more including `NodeTypeMap`, `parse_node_type_map`, and `NodeType`. How do you want to use public `NodeTypeMap`, and how do you imagine others would use it?

**Comment by wldmr** [comment]
Nice :). I've opened a PR and put a usage example in the comments. Let me know what you think, esp. if you see any potential problems with this.
