### ISSUE TITLE
Some generated code iterates over children indefinitely.

### ISSUE THREAD

**Issue by eikopf** [Jakobeha/type-sitter#8]
Sorry to come back with a bug so soon :(.

It looks like under certain conditions (i.e. my weird Tree-sitter grammar), the generated code will endlessly return the last child in an iterator. I think this is probably due to the mixing of named and unnamed children in a single node?

```javascript
// the relevant chunk of the grammar

const rules = {
    // ...
    source_file: ($) => seq(
        optional(field("shebang", $.shebang)),
        optional(field("module_comment", $.module_comment)),
        repeat($._decl),
    ),

    _decl: ($) => choice(/* some named subtypes */),
    // ...
}
```

Under these conditions, you can see that
1. `has_field` will always be false, as `_decl` is not a field of `source_file`;
2. `node.is_named()` will always be true, as all the subtypes of `_decl` are named;
3. `node.is_extra()` will always be false.

And so we loop forever! At least I got to brush up on LLDB again. 

![image](https://github.com/user-attachments/assets/a100eb72-1a5c-4ea4-b2ec-127962f1c0cc)

Anyway, this isn't too hard to hack around: the only change I had to make was to change `repeat($._decl)` to `field("decl", repeat($._decl))`.

**Comment by Jakobeha** [comment]
Thank you for finding this. I published a new version (v0.5.2) which should fix it. Let me know if it persists or there are any other issues.
